[package]
name = "alerter"
description = "Send messages to Slack"
version = "1.0.2"
authors = ["jan.veen@posteo.de"]
edition = "2018"
license = "GPL-3.0-or-later"

[[bin]]
name = "alerter"
path = "src/main.rs"

[[bin]]
name = "alert"
path = "src/alert.rs"

[profile.release]
lto = true

[dependencies]
clap = "2.27.0"
log = "0.4"
serde_derive = "1.0"
serde_yaml = "0.8.7"
serde_json = "1.0.40"
reqwest = "0.10"
nix = "0.17"
chrono = "0.4.6"
libc = "0.2.65"

[dependencies.serde]
version = "1.0.80"
features = ["derive"]

[dependencies.log4rs]
version = "0.11"
default-features = false
features = ["file", "pattern_encoder", "console_appender"]
