#!/bin/bash

set -e

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
CWD=$(pwd)

rm -rf $ROOT/pkg/Archlinux/{pkg,src,package.tar}

tar -cvf $ROOT/pkg/Archlinux/package.tar \
        --exclude-vcs \
        --exclude=target \
        $ROOT

cd $ROOT/pkg/Archlinux

if [[ -z $NO_SIGNATURE ]] ; then
    makepkg -fc --sign
else
    makepkg -fc
fi

cd $CWD
rm -rf $ROOT/pkg/Archlinux/{pkg,src,package.tar}
